version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: mobilearn-postgres
    restart: always
    environment:
      POSTGRES_USER: mobilearn
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    expose:
      - 5432
