export const BASE_HOME = "/(app)"; 

// MEMBER/GUEST PAGES

// INSTRUCTOR PAGES

// ADMIN PAGES
export const ADMIN_NAMESPACE = "(admin)";
export const ADMIN_HOME = `/${ADMIN_NAMESPACE}`;

export const ADMIN_USER_SETTINGS_NAMESPACE = "user_settings";
export const ADMIN_MEMBER_SETTINGS_NAMESPACE = "member";
export const ADMIN_INSTRUCTOR_SETTINGS_NAMESPACE = "instructor";
export const ADMIN_USER_SETTINGS = `${ADMIN_HOME}/${ADMIN_USER_SETTINGS_NAMESPACE}`;
export const ADMIN_MEMBER_SETTINGS = `${ADMIN_USER_SETTINGS}/${ADMIN_MEMBER_SETTINGS_NAMESPACE}`;
export const ADMIN_MEMBER_MANAGE = `${ADMIN_MEMBER_SETTINGS}/manage`;
export const ADMIN_INSTRUCTOR_SETTINGS = `${ADMIN_USER_SETTINGS}/${ADMIN_INSTRUCTOR_SETTINGS_NAMESPACE}`;
export const ADMIN_INSTRUCTOR_MANAGE = `${ADMIN_INSTRUCTOR_SETTINGS}/manage`;
export const ADMIN_INSTRUCTOR_REQUEST = `${ADMIN_INSTRUCTOR_SETTINGS}/request`;

export const ADMIN_CONTENT_SETTINGS = `${ADMIN_HOME}/content_settings`;
export const ADMIN_CHANNELS_MANAGE = `${ADMIN_CONTENT_SETTINGS}/channels_manage`;
export const ADMIN_COURSES_MANAGE = `${ADMIN_CONTENT_SETTINGS}/courses_manage`;
export const ADMIN_COURSES_REQUEST = `${ADMIN_CONTENT_SETTINGS}/courses_request`;

export const ADMIN_PAYMENT_SETTINGS = `${ADMIN_HOME}/payment_settings`;
export const ADMIN_PAYMENT_CONFIGS = `${ADMIN_PAYMENT_SETTINGS}/configs`;
export const ADMIN_PAYMENT_TRANSACTIONS = `${ADMIN_PAYMENT_SETTINGS}/transactions`;

export const ADMIN_SYSTEM_SETTINGS = `${ADMIN_HOME}/system_settings`;
export const ADMIN_SYSTEM_INFO = `${ADMIN_SYSTEM_SETTINGS}/info`;
export const ADMIN_SYSTEM_POLICY = `${ADMIN_SYSTEM_SETTINGS}/policy`;