export const VERSION = process.env.EXPO_PUBLIC_VERSION
  ? `/${process.env.EXPO_PUBLIC_VERSION}`
  : "/1.0";
export const BACKEND_BASE_URL =
  process.env.BACKEND_BASE_URL ??
  `http://${process.env.EXPO_PUBLIC_LOCAL_IP_ADDR}:8080`;

// AUTH NAMESPACE
const AUTH_NAMESPACE = "/auth";
const AUTH_BASE_URL = `${BACKEND_BASE_URL}${AUTH_NAMESPACE}${VERSION}`;

//AUTH ENDPOINTS
const AUTH_LOGIN_USER = "/user/login";
const AUTH_LOGIN_INSTRUCTOR = "/instructor/login";
const AUTH_SIGNUP_USER = "/user/signup";
const AUTH_SIGNUP_INSTRUCTOR = "/instructor/signup";
const AUTH_REFRESH_TOKEN = "/refresh";
const AUTH_LOGOUT = "/logout";

// ACCOUNT NAMESPACE
const ACCOUNT_NAMESPACE = "/account";
const ACCOUNT_BASE_URL = `${BACKEND_BASE_URL}${ACCOUNT_NAMESPACE}${VERSION}`;
const ACCOUNT_INSTRUCTOR_PROFILE = `${ACCOUNT_BASE_URL}/instructor/profile`;
const ACCOUNT_USER_PROFILE = `${ACCOUNT_BASE_URL}/user/profile`;
const ACCOUNT_INSTRUCTOR_SECURITY = `${ACCOUNT_BASE_URL}/instructor/security`;
const ACCOUNT_USER_SECURITY = `${ACCOUNT_BASE_URL}/user/security`;

//ACCOUNT ENDPOINTS
const ACCOUNT_EDIT_GENDER = "/editGender";
const ACCOUNT_EDIT_NAME = "/editName";
const ACCOUNT_EDIT_PROFILEPICTURE = "/editProfilePicture";
const ACCOUNT_EDIT_EMAIL = "/editEmail";
const ACCOUNT_EDIT_PASSWORD = "/editPassword";
const ACCOUNT_EDIT_PHONENUMBER_INSTRUCTOR = "/editPhoneNumber";
const ACCOUNT_EDIT_POSITION_INSTRUCTOR = "/editPosition";
const ACCOUNT_EDIT_COMPANY_INSTRUCTOR = "/editCompany";
const ACCOUNT_GET_GENDER = "/getGender";
const ACCOUNT_GET_NAME = "/getName";
const ACCOUNT_GET_PROFILEPICTURE = "/getProfilePicture";
const ACCOUNT_GET_PHONENUMBER_INSTRUCTOR = "/getPhoneNumber";
const ACCOUNT_GET_POSITION_INSTRUCTOR = "/getPosition";
const ACCOUNT_GET_NOTIFICATIONS_INSTRUCTOR =
  "/instructor/notification/getUnread";
const ACCOUNT_GET_NOTIFICATIONS_USER = "/user/notification/getUnread";

// CHANNEL ENDPOINTS
const CHANNEL_NAMESPACE = "/channel";
const CHANNEL_BASE_URL = `${BACKEND_BASE_URL}${CHANNEL_NAMESPACE}${VERSION}`;
const CHANNEL_GET_USER_CHANNELS = `/channel/getUserChannels`;
const CHANNEL_INVITE_USER = `/channel/inviteUser`;

// COMMUNITY ENDPOINTS
const COMMUNITY_NAMESPACE = "/community";
const COMMUNITY_BASE_URL = `${BACKEND_BASE_URL}${COMMUNITY_NAMESPACE}${VERSION}`;
const COMMUNITY_GET_COMMUNITIES = "/community/getCommunities";
const COMMUNITY_GET_INSTRUCTOR_DETAILS = "/community/getInstructorDetails";
const COMMUNITY_GET_INSTRUCTORS = "/community/getInstructors";

// COURSE ENDPOINTS
const COURSE_NAMESPACE = "/course";
const COURSE_BASE_URL = `${BACKEND_BASE_URL}${COURSE_NAMESPACE}${VERSION}`;
const COURSE_SEARCH = `/search`;
const COURSE_USER_ADD_FAVOURITE_COURSE = `/user/addFavouriteCourse`;
const COURSE_USER_COMPLETE_LESSON = `/user/completeLesson`;
const COURSE_USER_ENROLL_COURSE = `/user/enrollCourse`;
const COURSE_USER_GET_FAVOURITE_COURSES = `/user/getFavouriteCourses`;
const COURSE_USER_GET_ENROLLED_COURSES = `/user/getEnrolledCourses`;
const COURSE_USER_GET_RECOMMENDED_COURSES = `/user/getRecommendedCourses`;
const COURSE_USER_GET_REVIEW = `/user/getReview`;
const COURSE_USER_GET_TOP_ENROLLED_COURSES = `/user/getTopEnrolledCourses`;
const COURSE_USER_REMOVE_FAVOURITE_COURSE = `/user/removeFavouriteCourse`;
const COURSE_USER_SAVE_REVIEW = `/user/saveReview`;
const COURSE_USER_SUBMIT_HOMEWORK = `/user/submitHomework`;
const COURSE_USER_WITHDRAW_COURSE = `/user/withdrawCourse`;
const COURSE_INSTRUCTOR_PREVIEW_LESSON = `/instructor/previewLesson`;
const COURSE_INSTRUCTOR_COURSE_DETAILS = `/instructor/getCourseDetails`;

// PAYMENT NAMESPACE
const PAYMENT_NAMESPACE = "/payment";
const PAYMENT_BASE_URL = `${BACKEND_BASE_URL}${PAYMENT_NAMESPACE}${VERSION}`;
const PAYMENT_STRIPE_NAMESPACE = "/stripe";
const PAYMENT_STRIPE_BASE_URL = `${PAYMENT_BASE_URL}${PAYMENT_STRIPE_NAMESPACE}`;

//PAYMENT ENDPOINTS
const PAYMENT_STRIPE_FETCH_PAYMENT_SHEET = "/fetchPaymentSheet";

// EXPORTS
export const AUTH_USER_LOGIN_URL = `${AUTH_BASE_URL}${AUTH_LOGIN_USER}`;
export const AUTH_INSTRUCTOR_LOGIN_URL = `${AUTH_BASE_URL}${AUTH_LOGIN_INSTRUCTOR}`;
export const AUTH_USER_SIGNUP_URL = `${AUTH_BASE_URL}${AUTH_SIGNUP_USER}`;
export const AUTH_INSTRUCTOR_SIGNUP_URL = `${AUTH_BASE_URL}${AUTH_SIGNUP_INSTRUCTOR}`;
export const AUTH_REFRESH_TOKEN_URL = `${AUTH_BASE_URL}${AUTH_REFRESH_TOKEN}`;
export const AUTH_LOGOUT_URL = `${AUTH_BASE_URL}${AUTH_LOGOUT}`;

export const ACCOUNT_INSTRUCTOR_EDIT_GENDER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_GENDER}`;
export const ACCOUNT_INSTRUCTOR_EDIT_NAME_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_NAME}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PHONENUMBER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_PHONENUMBER_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_POSITION_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_POSITION_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PROFILEPICTURE_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_PROFILEPICTURE}`;
export const ACCOUNT_INSTRUCTOR_GET_GENDER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_GENDER}`;
export const ACCOUNT_INSTRUCTOR_GET_NAME_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_NAME}`;
export const ACCOUNT_INSTRUCTOR_GET_PHONENUMBER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_PHONENUMBER_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_GET_POSITION_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_POSITION_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_GET_PROFILEPICTURE_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_PROFILEPICTURE}`;
export const ACCOUNT_INSTRUCTOR_EDIT_COMPANY_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_COMPANY_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_EMAIL_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_EMAIL}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PASSWORD_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_PASSWORD}`;
export const ACCOUNT_INSTRUCTOR_GET_NOTIFICATIONS_URL = `${ACCOUNT_BASE_URL}${ACCOUNT_GET_NOTIFICATIONS_INSTRUCTOR}`;
export const ACCOUNT_USER_EDIT_GENDER_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_GENDER}`;
export const ACCOUNT_USER_EDIT_NAME_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_NAME}`;
export const ACCOUNT_USER_EDIT_PROFILEPICTURE_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_PROFILEPICTURE}`;
export const ACCOUNT_USER_GET_GENDER_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_GENDER}`;
export const ACCOUNT_USER_GET_NAME_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_NAME}`;
export const ACCOUNT_USER_GET_PROFILEPICTURE_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_PROFILEPICTURE}`;
export const ACCOUNT_USER_EDIT_EMAIL_URL = `${ACCOUNT_USER_SECURITY}${ACCOUNT_EDIT_EMAIL}`;
export const ACCOUNT_USER_EDIT_PASSWORD_URL = `${ACCOUNT_USER_SECURITY}${ACCOUNT_EDIT_PASSWORD}`;
export const ACCOUNT_USER_GET_NOTIFICATIONS_URL = `${ACCOUNT_BASE_URL}${ACCOUNT_GET_NOTIFICATIONS_USER}`;

export const CHANNEL_USER_GET_CHANNELS_URL = `${CHANNEL_BASE_URL}${CHANNEL_GET_USER_CHANNELS}`;
export const CHANNEL_USER_INVITE_URL = `${CHANNEL_BASE_URL}${CHANNEL_INVITE_USER}`;

export const COMMUNITY_GET_COMMUNITIES_URL = `${COMMUNITY_BASE_URL}${COMMUNITY_GET_COMMUNITIES}`;
export const COMMUNITY_GET_INSTRUCTOR_DETAILS_URL = `${COMMUNITY_BASE_URL}${COMMUNITY_GET_INSTRUCTOR_DETAILS}`;
export const COMMUNITY_GET_INSTRUCTORS_URL = `${COMMUNITY_BASE_URL}${COMMUNITY_GET_INSTRUCTORS}`;

export const COURSE_SEARCH_URL = `${COURSE_BASE_URL}${COURSE_SEARCH}`;
export const COURSE_GET_ALL_INSTRUCTOR_COURSES = `${COURSE_BASE_URL}/instructor/getInstructorCourses`;
export const COURSE_GET_ENROLLED_COURSE = `${COURSE_BASE_URL}/getEnrolledCourse`;
export const COURSE_GET_UNENROLLED_COURSE = `${COURSE_BASE_URL}/getUnenrolledCourse`;
export const COURSE_GET_TOP_COURSES_INSTRUCTOR = `${COURSE_BASE_URL}/instructor/getTopEnrolledCourses`;
export const COURSE_INSTRUCTOR_GET_PREVIEW_LESSON = `${COURSE_BASE_URL}${COURSE_INSTRUCTOR_PREVIEW_LESSON}`;
export const COURSE_INSTRUCTOR_GET_COURSE_DETAILS = `${COURSE_BASE_URL}${COURSE_INSTRUCTOR_COURSE_DETAILS}`;
export const COURSE_CREATE_COURSE = `${COURSE_BASE_URL}/instructor/create`;
export const COURSE_INSTRUCTOR_EDIT_COURSE = `${COURSE_BASE_URL}/instructor/edit`;
export const COURSE_USER_ADD_FAVOURITE_COURSE_URL = `${COURSE_BASE_URL}${COURSE_USER_ADD_FAVOURITE_COURSE}`;
export const COURSE_USER_COMPLETE_LESSON_URL = `${COURSE_BASE_URL}${COURSE_USER_COMPLETE_LESSON}`;
export const COURSE_USER_ENROLL_COURSE_URL = `${COURSE_BASE_URL}${COURSE_USER_ENROLL_COURSE}`;
export const COURSE_USER_GET_FAVOURITE_COURSES_URL = `${COURSE_BASE_URL}${COURSE_USER_GET_FAVOURITE_COURSES}`;
export const COURSE_USER_GET_ENROLLED_COURSES_URL = `${COURSE_BASE_URL}${COURSE_USER_GET_ENROLLED_COURSES}`;
export const COURSE_USER_GET_RECOMMENDED_COURSES_URL = `${COURSE_BASE_URL}${COURSE_USER_GET_RECOMMENDED_COURSES}`;
export const COURSE_USER_GET_REVIEW_URL = `${COURSE_BASE_URL}${COURSE_USER_GET_REVIEW}`;
export const COURSE_USER_GET_TOP_ENROLLED_COURSES_URL = `${COURSE_BASE_URL}${COURSE_USER_GET_TOP_ENROLLED_COURSES}`;
export const COURSE_USER_REMOVE_FAVOURITE_COURSE_URL = `${COURSE_BASE_URL}${COURSE_USER_REMOVE_FAVOURITE_COURSE}`;
export const COURSE_USER_SAVE_REVIEW_URL = `${COURSE_BASE_URL}${COURSE_USER_SAVE_REVIEW}`;
export const COURSE_USER_SUBMIT_HOMEWORK_URL = `${COURSE_BASE_URL}${COURSE_USER_SUBMIT_HOMEWORK}`;
export const COURSE_USER_WITHDRAW_COURSE_URL = `${COURSE_BASE_URL}${COURSE_USER_WITHDRAW_COURSE}`;

export const PAYMENT_STRIPE_FETCH_PAYMENT_SHEET_URL = `${PAYMENT_STRIPE_BASE_URL}${PAYMENT_STRIPE_FETCH_PAYMENT_SHEET}`;

// COMMUNITIES
const COMMUNITIES_NAMESPACE = "/community";
const COMMUNITIES_BASE_URL = `${BACKEND_BASE_URL}${COMMUNITIES_NAMESPACE}${VERSION}`;
export const COMMUNITIES_GET_ALL = `${COMMUNITIES_BASE_URL}/community/getCommunities`;
