export const VERSION = process.env.EXPO_PUBLIC_VERSION
  ? `/${process.env.EXPO_PUBLIC_VERSION}`
  : "/1.0";
export const BACKEND_BASE_URL =
  process.env.BACKEND_BASE_URL ??
  `http://${process.env.EXPO_PUBLIC_LOCAL_IP_ADDR}:8080`;

// AUTH NAMESPACE
const AUTH_NAMESPACE = "/auth";
const AUTH_BASE_URL = `${BACKEND_BASE_URL}${AUTH_NAMESPACE}${VERSION}`;

//AUTH ENDPOINTS
const AUTH_LOGIN_USER = "/user/login";
const AUTH_LOGIN_INSTRUCTOR = "/instructor/login";
const AUTH_SIGNUP_USER = "/user/signup";
const AUTH_SIGNUP_INSTRUCTOR = "/instructor/signup";
const AUTH_REFRESH_TOKEN = "/refresh";
const AUTH_LOGOUT = "/logout";

// ACCOUNT NAMESPACE
const ACCOUNT_NAMESPACE = "/account";
const ACCOUNT_BASE_URL = `${BACKEND_BASE_URL}${ACCOUNT_NAMESPACE}${VERSION}`;
const ACCOUNT_INSTRUCTOR_PROFILE = `${ACCOUNT_BASE_URL}/instructor/profile`;
const ACCOUNT_USER_PROFILE = `${ACCOUNT_BASE_URL}/user/profile`;
const ACCOUNT_INSTRUCTOR_SECURITY = `${ACCOUNT_BASE_URL}/instructor/security`;
const ACCOUNT_USER_SECURITY = `${ACCOUNT_BASE_URL}/user/security`;

//ACCOUNT ENDPOINTS
const ACCOUNT_EDIT_GENDER = "/editGender";
const ACCOUNT_EDIT_NAME = "/editName";
const ACCOUNT_EDIT_PROFILEPICTURE = "/editProfilePicture";
const ACCOUNT_EDIT_EMAIL = "/editEmail";
const ACCOUNT_EDIT_PASSWORD = "/editPassword";
const ACCOUNT_EDIT_PHONENUMBER_INSTRUCTOR = "/editPhoneNumber";
const ACCOUNT_EDIT_POSITION_INSTRUCTOR = "/editPosition";
const ACCOUNT_EDIT_COMPANY_INSTRUCTOR = "/editCompany";
const ACCOUNT_GET_GENDER = "/getGender";
const ACCOUNT_GET_NAME = "/getName";
const ACCOUNT_GET_PROFILEPICTURE = "/getProfilePicture";
const ACCOUNT_GET_PHONENUMBER_INSTRUCTOR = "/getPhoneNumber";
const ACCOUNT_GET_POSITION_INSTRUCTOR = "/getPosition";

// CHANNEL ENDPOINTS
const CHANNEL_NAMESPACE = "/channel";
const CHANNEL_BASE_URL = `${BACKEND_BASE_URL}${CHANNEL_NAMESPACE}${VERSION}`;
const CHANNEL_GET_USER_CHANNELS = `/channel/getUserChannels`;
const CHANNEL_INVITE_USER = `/channel/inviteUser`;

// PAYMENT NAMESPACE
const PAYMENT_NAMESPACE = "/payment";
const PAYMENT_BASE_URL = `${BACKEND_BASE_URL}${PAYMENT_NAMESPACE}${VERSION}`;
const PAYMENT_STRIPE_NAMESPACE = "/stripe";
const PAYMENT_STRIPE_BASE_URL = `${PAYMENT_BASE_URL}${PAYMENT_STRIPE_NAMESPACE}`;

//PAYMENT ENDPOINTS
const PAYMENT_STRIPE_FETCH_PAYMENT_SHEET = "/fetchPaymentSheet";

// EXPORTS
export const AUTH_USER_LOGIN_URL = `${AUTH_BASE_URL}${AUTH_LOGIN_USER}`;
export const AUTH_INSTRUCTOR_LOGIN_URL = `${AUTH_BASE_URL}${AUTH_LOGIN_INSTRUCTOR}`;
export const AUTH_USER_SIGNUP_URL = `${AUTH_BASE_URL}${AUTH_SIGNUP_USER}`;
export const AUTH_INSTRUCTOR_SIGNUP_URL = `${AUTH_BASE_URL}${AUTH_SIGNUP_INSTRUCTOR}`;
export const AUTH_REFRESH_TOKEN_URL = `${AUTH_BASE_URL}${AUTH_REFRESH_TOKEN}`;
export const AUTH_LOGOUT_URL = `${AUTH_BASE_URL}${AUTH_LOGOUT}`;

export const ACCOUNT_INSTRUCTOR_EDIT_GENDER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_GENDER}`;
export const ACCOUNT_INSTRUCTOR_EDIT_NAME_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_NAME}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PHONENUMBER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_PHONENUMBER_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_POSITION_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_POSITION_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PROFILEPICTURE_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_EDIT_PROFILEPICTURE}`;
export const ACCOUNT_INSTRUCTOR_GET_GENDER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_GENDER}`;
export const ACCOUNT_INSTRUCTOR_GET_NAME_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_NAME}`;
export const ACCOUNT_INSTRUCTOR_GET_PHONENUMBER_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_PHONENUMBER_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_GET_POSITION_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_POSITION_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_GET_PROFILEPICTURE_URL = `${ACCOUNT_INSTRUCTOR_PROFILE}${ACCOUNT_GET_PROFILEPICTURE}`;
export const ACCOUNT_INSTRUCTOR_EDIT_COMPANY_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_COMPANY_INSTRUCTOR}`;
export const ACCOUNT_INSTRUCTOR_EDIT_EMAIL_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_EMAIL}`;
export const ACCOUNT_INSTRUCTOR_EDIT_PASSWORD_URL = `${ACCOUNT_INSTRUCTOR_SECURITY}${ACCOUNT_EDIT_PASSWORD}`;
export const ACCOUNT_USER_EDIT_GENDER_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_GENDER}`;
export const ACCOUNT_USER_EDIT_NAME_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_NAME}`;
export const ACCOUNT_USER_EDIT_PROFILEPICTURE_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_EDIT_PROFILEPICTURE}`;
export const ACCOUNT_USER_GET_GENDER_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_GENDER}`;
export const ACCOUNT_USER_GET_NAME_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_NAME}`;
export const ACCOUNT_USER_GET_PROFILEPICTURE_URL = `${ACCOUNT_USER_PROFILE}${ACCOUNT_GET_PROFILEPICTURE}`;
export const ACCOUNT_USER_EDIT_EMAIL_URL = `${ACCOUNT_USER_SECURITY}${ACCOUNT_EDIT_EMAIL}`;
export const ACCOUNT_USER_EDIT_PASSWORD_URL = `${ACCOUNT_USER_SECURITY}${ACCOUNT_EDIT_PASSWORD}`;

export const CHANNEL_USER_GET_CHANNELS = `${CHANNEL_BASE_URL}${CHANNEL_GET_USER_CHANNELS}`;
export const CHANNEL_USER_INVITE = `${CHANNEL_BASE_URL}${CHANNEL_INVITE_USER}`;

export const PAYMENT_STRIPE_FETCH_PAYMENT_SHEET_URL = `${PAYMENT_STRIPE_BASE_URL}${PAYMENT_STRIPE_FETCH_PAYMENT_SHEET}`;

// COMMUNITIES
const COMMUNITIES_NAMESPACE = "/community";
const COMMUNITIES_BASE_URL = `${BACKEND_BASE_URL}${COMMUNITIES_NAMESPACE}${VERSION}`;
export const COMMUNITIES_GET_ALL = `${COMMUNITIES_BASE_URL}/community/getCommunities`;
